name: Terraform Plan

on:
  push:
    branches:
      - '**'
    paths:
      - 'Infra/**'

jobs:
  terraform-plan:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: Infra
        run: terraform init

      - name: Terraform Plan
        working-directory: Infra
        run: terraform plan